### ISSUE TITLE
modularity

### ISSUE THREAD

**Issue by maxdevjs** [adi1090x/polybar-themes#1]
Hi,

this is a pretty awesome project :)

If I am not wrong, you are using personal scripts (not included) and the project is currently tied to Arch (flavored) distro, which is not exactly suitable to my use case (I do not have your scripts, I've switched to Solus).

Note: this is not in any way a statement on how the project should evolve.

I started a test to make it more modular and perhaps easier to be adopted by other people.

You can find an initial [pull-config-off](https://github.com/maxdevjs/polybar-themes/tree/pull-config-off) branch in my fork. Basically, what I done is to:

- extract the actual bar config (bar/main, monitor, fonts, modules location, ...) to config/config
- extract actual modules to config/modules.config
- clean "themes" (leave only colors)

modules.config should allow to deliver a set of default modules.

TODO:

- create config/modules.user.config (specific to user distro, needs, scripts, and to not clutter modules.config)
- check how to facilitate includes to user
- ...

Let me know if it has usefulness for your project.

**Comment by adi1090x** [comment]
Yeah, actually I've created these config files to provide a specific and default set of modules, if people wants more they can add more by themselves...
Second, I wanted the config in a single file, so i didn't create a separate file for modules  and etc... However, In my next set of configs, I'm doing so. 
Third, I've added some Scripts in the repo too. 
And of course, you can include a files in main config to allow users to add their modules, maybe I'll do that in next theme set.
Thanks for the suggestions.
