### ISSUE TITLE
Some of Modules not working 

### ISSUE THREAD

**Issue by Anzar-Makrani** [adi1090x/polybar-themes#100]
`error: Disabling module "network" (reason: Invalid network interface "wlan0")
` 
heres my arch system 
os: Arch linux x86_64
kernel: 5.11.0-arch2-1
shell: fish
WM: i3-gaps
Cpu:Pentium E5200 (2) @ 2.500GHz
Gpu: Intel 4 Series Chipset
mem: 4Gig and 4Gig swap

**Comment by geektimus** [comment]
It is probable that in your system the network interface is not called `wlan0` in my case my wlan interface is `wlp5s0` and my wired interface is called `enp3s0`.

To find out the name of the interface you can use `ip address` and when you find it you can update the `modules.ini` file with the right interface name.

**Comment by Anzar-Makrani** [comment]
> It is probable that in your system the network interface is not called `wlan0` in my case my wlan interface is `wlp5s0` and my wired interface is called `enp3s0`.
> 
> To find out the name of the interface you can use `ip address` and when you find it you can update the `modules.ini` file with the right interface name.

thx
