### ISSUE TITLE
Odd 1px space between glyphs

### ISSUE THREAD

**Issue by NextRank** [adi1090x/polybar-themes#105]
I am using the following shapes style, and I noticed that I have these 1px spaces between the background and the glyphs: https://raw.githubusercontent.com/adi1090x/files/master/polybar-themes/previews/shapes/md5.gif

However, it is not the case in this image: https://i.redd.it/c0xfz6pap5k21.png

Is there something I can add into the configs to make it go away? Or do I just have to edit the font to remove that spacing?

**Comment by NextRank** [comment]
Closing because nobody has seen this in over a week

**Comment by RomjanHossain** [comment]
bruh, where did you find that glyphs?

**Comment by lalaithan** [comment]
> 

It's a part of the shapes theme.

**Comment by lamduong33** [comment]
Having the same issue. I'm guessing nobody is using the shapes theme.

**Comment by Filippo39** [comment]
@lamduong33 @NextRank lamduong33Try moving the glyph left/right by 1 px, for example:
```
[glyph]
gLeft = %{O-1}
```
