### ISSUE TITLE
Cant get workspace numbers show up in bspwm (polybar 1)

### ISSUE THREAD

**Issue by Aesyir** [adi1090x/polybar-themes#11]
I cant get the workspace numbers to show up in bspwm, is there something I need to change in the config?

**Comment by pjhalsli** [comment]
that bar looks it is for i3 so you need to add a module for bspwm

here you can take a look at mine 
https://pastebin.com/QdDquUAq

**Comment by Aesyir** [comment]
Thanks a bunch after messing with the cfg I got it to work!
