### ISSUE TITLE
Icon for logout option is displaying different character

### ISSUE THREAD

**Issue by Abel-Arias** [adi1090x/polybar-themes#128]
The character for the "Logout" option from the `powermenu.sh` script is displaying a character rather than an icon, I'm pretty sure I've got all fonts installed and this is only happening with that one character, so I'm kind of at a loss here.

Here's what it looks like:
![2021-06-01-170507](https://user-images.githubusercontent.com/41349635/120384116-226c4480-c2fc-11eb-8cd8-532a2bff36fd.png)

If anyone can lend a hand with it I'd really appreciate it.

**Comment by jaromeyer** [comment]
Does it show the proper icon when you edit the `powermenu.sh` file? You could always just replace the icon with one from the [Nerd Fonts Cheat Sheet](https://www.nerdfonts.com/cheat-sheet).

**Comment by Abel-Arias** [comment]
The `powermenu.sh` displays the wrong one, when I replaced it with the proper one from the cheat sheet it showed up as a blank space but it's showing alright on the actual menu so it should be good enough.
