### ISSUE TITLE
In polybar-4, how to make each workspace display a different logo

### ISSUE THREAD

**Issue by nce3xin** [adi1090x/polybar-themes#13]
Thanks for sharing. In polybar-4, may I know how to make each workspace display a different logo? For now, I have the same logo for all workspaces… Thanks a lot.

**Comment by patrick96** [comment]
You need to adapt the `icon-*` keys in the `xworkspaces` module to map your desktop names to the icons you want (also see the [polybar wiki](https://github.com/jaagr/polybar/wiki/Module:-xworkspaces#additional-formatting))
