### ISSUE TITLE
Pywal is installed, but pywal.sh returns error.

### ISSUE THREAD

**Issue by redfox-23** [adi1090x/polybar-themes#131]
Pywal is installed through pip3 (`sudo pip3 install pywal`), however if I try to run any theme's pywal.sh, it returns error: 
`[!] 'pywal' is not installed.`

Output for `pip3 show pywal`:

`Name: pywal
Version: 3.3.0
Summary: Generate and change color-schemes on the fly
Home-page: https://github.com/dylanaraps/pywal
Author: Dylan Araps
Author-email: dylan.araps@gmail.com
License: MIT
Location: /usr/local/lib/python3.8/dist-packages
Requires: 
Required-by: 
`

**Comment by KaniDev** [comment]
see #110; there's an easy fix

**Comment by redfox-23** [comment]
Thx, it worked :+1:
