### ISSUE TITLE
warn: Dropping unmatched character ﭳ (U+fb73)

### ISSUE THREAD

**Issue by rodrigogonegit** [adi1090x/polybar-themes#14]
Hey, I think there's a font missing in the polybar5 theme.

It looks like it can't load a specific character:
warn: Dropping unmatched character ﭳ (U+fb73)

I added this one:
font-5= DejaVu Sans Mono Nerd Font:style=Medium:size=12;3

**Comment by Xyverz** [comment]
I get this with every single one of these themes, it would seem. And I have installed these fonts. :-(

**Comment by jordanjoewatson** [comment]
I had the same issue with polybar5. It's not a missing font, just the name is incorrect. The naming of the font in config.ini was incorrect.
The naming in the lines 143 - 151 were
    Iosevka Nerd Font:style=Medium:size=10;3
When it should have been 
    Iosevka:style=Medium:size=10;3

If it helps, I found which font to use with the command 'fc-list | grep Iosevka'
    /usr/share/fonts/iosevka-regular/iosevka-regular.ttf: Iosevka:style=Regular
    /usr/share/fonts/iosevka-regular/iosevka-regular.ttf: <replace_font_name_with_this>:style=Regular

**Comment by adi1090x** [comment]
I've included every font, related to specific polybar. All you need to install them correctly, either globally or locally. No need to install or add other fonts.
