### ISSUE TITLE
update module not opening preffered applicatino

### ISSUE THREAD

**Issue by RomjanHossain** [adi1090x/polybar-themes#142]
When i clicked on the update module in the bar it has this error
`Failed to launch preferred application for category "TerminalEmulator".`

**Comment by notsogreatdavi** [comment]
Kinda late, but you just need to install xfce4-settings on your system so you can choose the preferred application.

Never too late to close an issue, right?

**Comment by RomjanHossain** [comment]
okay! thanks, brother
