### ISSUE TITLE
PowerMenu, Launch, Change Style Rofi window was changed text-background color

### ISSUE THREAD

**Issue by dungxibo123** [adi1090x/polybar-themes#145]
Hello,

I am a 1-year user of Polybar and Polybar-themes. I think this is a wonderful project.

My Issue is: Some part of launchers' background `Rofi` is not as same as the `primary color`

I have used `Manjaro XFCE + i3wm` for about six months before reinstalling Arch Linux.
I installed polybar by `yay -S polybar` and clone my own (re-config) polybar dotfile  (--cuts theme) which I saved in Github.
Before switching into Arch, my `rofi` window (PowerMenu, Launch, Change Style, etc) is very normal. But when I using Arch Linux, the window is a little bit changed. The element background-color was always `white`.

For more specific please checkout my pictures [HERE](https://drive.google.com/drive/folders/1eVI9UlxdkYHZQyl8UvvBOVqjTb07V9cV)

Which I tried to do

* Reinstall `polybar-themes` by instructions in this repository
* Reinstall `polybar`
* Reading and config many things in config files

It does not have anything work, The result is the same. I wonder that may I missing something (fonts, color, etc)

Hope to receiving replies soon.

Thanks,
Dung

**Comment by creepandpeep** [comment]
Had same issue and just fixed it:

In .config/polybar/forest/scripts/rofi/powermenu.rasi

Add:
	    `background-color:               @al;`

to the element-icon and element-text sections.

I'm sure it will be a similar process for the launcher etc

**Comment by Fymyte** [comment]
Thanks for the tips worked for me too

**Comment by dungxibo123** [comment]
This my way to fix this
at any `./scripts/rofi/*.rasi` file, add two lines to the end of the file
```
element-text, element-icon {
	background-color: inherit;
	text-color: inherit;
}
```
This was suggested by @davatorium - publisher of Rofi
