### ISSUE TITLE
Update Module Saying None

### ISSUE THREAD

**Issue by cheezymousehouse825** [adi1090x/polybar-themes#154]
The module that is in charge of telling you of updates always reads none, even though I am on arch linux. When I run `checkupdates`, it prints out everything that needs to be updated and what version and all of that. But when I run `updates.sh`, all it does is print none to the terminal. Does anyone know what is wrong?

**Comment by thanksandnubbo** [comment]
The creator said that module only work on Arch Linux.

**Comment by cheezymousehouse825** [comment]
> The creator said that module only work on Arch Linux.

I am using Arch Linux

**Comment by cheezymousehouse825** [comment]
I have created a solution just now though, and will soon make a PR to fix

**Comment by cheezymousehouse825** [comment]
I have solved my issue by implementing a custom workaround in the `updates.sh` file. To fix this issue, in the `updates.sh` file, I replaced the 5th line in `updates.sh` that reads "`get_total_updates() { UPDATES=$(checkupdates 2>/dev/null | wc -l); }`" with "`get_total_updates() { UPDATES=$(~/.config/polybar/insertthemehere/scripts/checkupdates 2>/dev/null | wc -l); }`". 

Link to PR is here: https://github.com/adi1090x/polybar-themes/pull/155
