### ISSUE TITLE
[cuts] IPC issue on i3

### ISSUE THREAD

**Issue by jay-tux** [adi1090x/polybar-themes#162]
None of the mouse actions (click, scroll, ...) are working when I start the bar with i3, like this (`~/.config/i3/config`):
```sh
exec_always --no-startup-id $HOME/.config/polybar/launch.sh --cuts
```
However, when I start the polybar later, using the command below; all the mouse actions work...
```sh
$HOME/.config/polybar/launch.sh --cuts
```

How to fix?

**Comment by setyawanfa** [comment]
Try to change using bash 

`exec_always --no-startup-id "bash $HOME/.config/polybar/launch.sh --cuts"`

this work fine at least for me.

**Comment by adi1090x** [comment]
Solved?

**Comment by jay-tux** [comment]
In the end, I didn't really have to change anything... It just *magically* worked again
