### ISSUE TITLE
pywal script not working

### ISSUE THREAD

**Issue by cnr90** [adi1090x/polybar-themes#164]
When I try to run the pywal script, I get an error like this:

![2022-04-07-214703_1126x61_scrot](https://user-images.githubusercontent.com/102424352/162274959-03142a91-881d-4fad-a9fa-d80a4201cad7.png)

and the bar looks like this

![2022-04-07-214808_1366x59_scrot](https://user-images.githubusercontent.com/102424352/162275128-f4f0bbb4-3058-4316-ba05-84ecf64bfb97.png)

**Comment by madhavpcm** [comment]
I have the same issue. 
```bash
./pywal.sh ~/Pictures/wallpaper/1776164.jpg
./pywal.sh: line 44: /home/madhavpcm/.cache/wal/colors.sh: No such file or directory
Successfully wrote "cmd:restart" to "/tmp/polybar_mqueue.1202"
Successfully wrote "cmd:restart" to "/tmp/polybar_mqueue.1203"
```

**Comment by adi1090x** [comment]
Fixed.
