### ISSUE TITLE
Rofi Launcher looking weird

### ISSUE THREAD

**Issue by m-anwr** [adi1090x/polybar-themes#166]
I am using the Blocks theme with polybar on i3wm. it looks like that:
![image](https://user-images.githubusercontent.com/3941126/178505832-ba2bcc93-38e0-48b5-a428-d17da18cdead.png)

Does anyone know how to solve this issue, I can barely see the highlights

It should look like this:
![image](https://user-images.githubusercontent.com/3941126/178506324-2022fe43-e67a-4710-9b83-92287b298caf.png)

**Comment by day-mon** [comment]
Looking weird for me too on XFCE with Shapes

**Comment by day-mon** [comment]
Found a fix.

This is a duplicate of #145. Go look at that you will be able to solve it.

**Comment by renanrod4** [comment]
try to add this in the end of file:
`
element-text, element-icon {
	background-color: inherit;
	text-color: inherit;
}
`

**Comment by adi1090x** [comment]
Fixed.
