### ISSUE TITLE
please help with fonts / glyphs

### ISSUE THREAD

**Issue by prankousky** [adi1090x/polybar-themes#167]
Hi,

I am trying to configure `material` as a polybar theme for my bottom monitor. Unfortunately, the part of `module/workspaces` only contains `icon-1` to `icon-4`; My bottom monitor is supposed to have `5-0` (5,6,7,8,9,0). Where can I find glyphs for this, or, what font is this?

Screenshot of that bar
![image](https://user-images.githubusercontent.com/11297070/181772830-b89b4955-7f6f-4719-8ca2-a267acad6e36.png)

Below is the relevant part of the `modules.ini` file. I manually added test values for everything after `icon-4`, but couldn't find the relevant glyphs / fonts.

```ini
; icon-[0-9]+ = <desktop-name>;<icon>
; NOTE: The desktop name needs to match the name configured by the WM
; You can get a list of the defined desktops using:
; $ xprop -root _NET_DESKTOP_NAMES
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-4 = 5;
; icon-4 = 5;
icon-5 = 6;6
icon-6 = 7
icon-7 = 8
icon-8 = 9
icon-0 = 1;
icon-default = 
```

It seems like github won't actually display those icons, so below is a screenshot from within `nvim`

![image](https://user-images.githubusercontent.com/11297070/181773232-05f9784c-0994-44a1-9568-cc11197d1c8d.png)

While `nvim` displays some of those icons incorrectly (for example the icon for 4; in polybar, this is actually a `4` in a rounded square, but in nvim it looks like a speech bubble. And the `icon-default` looks like a map in nvim, but like an empty square in polybar).

Thank you in advance for your help :)

**Comment by adi1090x** [comment]
https://zavoloklom.github.io/material-design-iconic-font/cheatsheet.html#numbers
