### ISSUE TITLE
rofi and styles manager corners looks ugly

### ISSUE THREAD

**Issue by WhitteGoose** [adi1090x/polybar-themes#169]
![image](https://user-images.githubusercontent.com/89806596/181878061-7c52cf0c-772b-4ad4-8576-6ac86e904476.png)
![image](https://user-images.githubusercontent.com/89806596/181878081-483f1114-a371-4cc8-895a-b36c577b9dde.png)
before that I had same issue as #166, and there I found the fix. 
But the corners are still awful

**Comment by NChechulin** [comment]
@sukalaper Compton won't help here. I encountered the same issue a while ago, when `rofi` introduced some new parameter for text background color. It defaults to white.
So the only way to fix this is to patch rofi config files.

**Comment by sukalaper** [comment]
> @sukalaper Compton won't help here. I encountered the same issue a while ago, when `rofi` introduced some new parameter for text background color. It defaults to white. So the only way to fix this is to patch rofi config files.

I'll be back some time if this issue hasn't been resolved with a bit of my configuration.
hope it can help later.

**Comment by adi1090x** [comment]
Depends on Compositor.

**Comment by WhitteGoose** [comment]
So I can't use this with picom?
