### ISSUE TITLE
polybar 4 icomoon feather font

### ISSUE THREAD

**Issue by AntouanK** [adi1090x/polybar-themes#17]
Just selecting all the icons and downloading the font doesn't work because the bar uses the wrong icons.

How are we supposed to download that icomoon feather set?

Thank you for your work btw :+1: .

**Comment by DevGrohl** [comment]
@AntouanK this may help you: https://github.com/adi1090x/polybar-themes/issues/8#issuecomment-497528419

**Comment by AntouanK** [comment]
@DevGrohl Thank you. 
That worked, with the tiny detail that I had to name the font in the config like this
```
font-1 = "icomoon\-feather:size=10;2"
```
