### ISSUE TITLE
Panel themes are kind of a mess.

### ISSUE THREAD

**Issue by AwkwardTeenageBoy** [adi1090x/polybar-themes#170]
So I installed it on my i3-gaps environment and I was trying to use the liri panel, but I had to switch the config.ini for the liri.ini file. and then I had to change some of the .rasi files because they had those ugly backgrounds, and to top it off I can't set up my shortcuts on i3 to open the launcher/powermenu because theres "no theme selected" when i put the liri theme in. If you could fix this that would be helpful. Thanks!

**Comment by sukalaper** [comment]
> So I installed it on my i3-gaps environment and I was trying to use the liri panel, but I had to switch the config.ini for the liri.ini file. and then I had to change some of the .rasi files because they had those ugly backgrounds, and to top it off I can't set up my shortcuts on i3 to open the launcher/powermenu because theres "no theme selected" when i put the liri theme in. If you could fix this that would be helpful. Thanks!

regarding launcher and powermenu, it all seems to be rofi related.
can i see your full config?

**Comment by adi1090x** [comment]
Fixed!
