### ISSUE TITLE
error: module/mpd: Connection refused

### ISSUE THREAD

**Issue by dotarjun** [adi1090x/polybar-themes#177]
A duplicate of #94 
Same issue

**Comment by Matteal** [comment]
This means you have not properly configured your mpd server.
You have two solutions: 

1 - Delete mpd module in the .config/polybar/<theme>/config.ini file
It should be in module-left or module-right
This way you won't have the error nor the module to control music

2 - Configure properly a mpd server. This way you would have both no error and a functional music controller.

**Comment by dotarjun** [comment]
Not using polybar anymore
