### ISSUE TITLE
How to set bar possition?

### ISSUE THREAD

**Issue by ostap-tymchenko** [adi1090x/polybar-themes#178]
Hello, i was wondering where i can set the position of my bar? i am using the material where the edges don't touch the edge and it is hovering, i was wondering if i can change that?

**Comment by sukalaper** [comment]
> Hello, i was wondering where i can set the position of my bar? i am using the material where the edges don't touch the edge and it is hovering, i was wondering if i can change that?

yap, of course! btw can i see your `config`?

**Comment by ostap-tymchenko** [comment]
Sorry i dont use polybar anymore, i was just testing it out at the time.
