### ISSUE TITLE
no spaces in between modules: polybar-7

### ISSUE THREAD

**Issue by kiedtl** [adi1090x/polybar-themes#19]
I'm not sure if I forgot something or if its something i don't have installed, but the polybar-7 bar is really ugly and doesn't have spaces.

![current](https://user-images.githubusercontent.com/32681240/59048591-2a4f9600-8854-11e9-81a9-b49dc8495978.jpg)

**Comment by adi1090x** [comment]
Look, like you modified it incorrectly, polybar 7 doesn't have globally module margin set, it uses margin individually for each module.
