### ISSUE TITLE
Volume controll module not starting at startup i3wm

### ISSUE THREAD

**Issue by danu9622** [adi1090x/polybar-themes#190]
so i have instaled the polybar theme (hack) but evry time i startup i3 it never loads it isnt present on my polybar please help.

**Comment by danu9622** [comment]
also the only way to make it start is to launch it manualy

**Comment by sukalaper** [comment]
> so i have instaled the polybar theme (hack) but evry time i startup i3 it never loads it isnt present on my polybar please  share your `config`

can i see your `config` ?

**Comment by danu9622** [comment]
Its the basic one 
Did not change anything
Also it started working after i changed to manjaro i3

**Comment by josesilveiraa** [comment]
+1

**Comment by jfragoulis** [comment]
Do you get any errors? Try starting polybar separately so that you can observe the logs.

Open a terminal and type `polybar -q top ~/.config/polybar/hack/config.ini` and see what errors you get.

**Comment by alphaprads** [comment]
why are we running it with -q we want logs right?

**Comment by danu9622** [comment]
figure it out 

i just made a .sh file that opens polybar kills it and reopen the bar
and it works perfectly
and the i made i3 to open my sh file insted of the bar.

if anyone wants my .sh replay to this coment.

**Comment by MrNereof** [comment]
> if anyone wants my .sh replay to this coment.

+1

**Comment by PR0B0M** [comment]
i am having similar issue with openbox and i have tried the running it twice method using a different .sh but it still doesn't work

is it possible to get your @danu9622 .sh file so i can cross check with mine or is there any other way
