### ISSUE TITLE
error: module/mpd: Connection refused

### ISSUE THREAD

**Issue by thien0709** [adi1090x/polybar-themes#199]
HI !
When i run zsh ~/.config/polybar/launch.sh --forest
terminal error rapidly and show error: module/mpd: Connection refused
How to fix it please

**Comment by Sorcecoder** [comment]
Same problem here

**Comment by alphaprads** [comment]
have you installed mpd

**Comment by woshichuanqilz** [comment]
Just go to the `forest` folder in your config file find `config.ini`, then search for `mpd` just remove it will be fine. So the music not been shown which is a simple way for this. 

If you want to show the music just read some doc about mpd. And start mpd service then set the port in the `modules.ini` file same with your mpd setting for host and port.
