### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by AlvinPix** [adi1090x/polybar-themes#202]
I have been customizing the polybar called cuts, I want different icons for the tabs apart from the ones there are. I have been researching the source of the Icomoon Feather icons and I want to copy them to paste them in the polybar but all those icons are not text but .svg files

https://feathericons.com/

![2023-09-12_10-44](https://github.com/adi1090x/polybar-themes/assets/96206578/a4931be5-2efc-46df-a662-82ae2fa57e23)

**Comment by Ke1pX** [comment]
@AlvinPix Hello, I think this video will be helpful to you - [ArcoLinux : 2286 Changing the icons in polybar - use font-manager - awesome font - MUTE](https://www.youtube.com/watch?v=MqHXaYns7R0)

**Comment by AlvinPix** [comment]
> @AlvinPixHola, creo que este video te será útil - [ArcoLinux: 2286 Cambiando los íconos en Polybar - usa font-manager - fuente impresionante - MUTE](https://www.youtube.com/watch?v=MqHXaYns7R0)

Muchas gracias por la sugerencia del video probare con lo que pude visualizar en el video de youtube
