### ISSUE TITLE
Polybar Command Updating

### ISSUE THREAD

**Issue by ijcon40** [adi1090x/polybar-themes#31]
When using one quick links on polybar 2 theme (default: google, github, reddit, facebook, youtube), the battery life, volume, and all other functions of the polybar are non-responsive until the application is closed. This behavior seems likely that the plugin needs to be run asynchronously. I can reproduce this regularly on my local setup.

**Comment by adi1090x** [comment]
Maybe i forgot to add '&' at the end of exec... Which one are you using?
