### ISSUE TITLE
warn: Dropping unmatched character

### ISSUE THREAD

**Issue by hillz2** [adi1090x/polybar-themes#37]
Hi,

I'm trying to use `Polybar-5` but I'm getting `warn: Dropping unmatched character` even though I've installed the required fonts:
```
[manjaro@linux ~]$ pacman -Q | grep -i 'iosevka'
ttf-iosevka 2.3.3-1
[manjaro@linux ~]$ pacman -Q | grep -i 'icomoon'
ttf-icomoon-icons 1.0-1
```
Here's what the error looks like: https://i.ibb.co/qMyBf61/2020-03-15-085332-328x187-scrot.png
I'm using manjaro i3wm. How do I fix this ?

**Comment by adi1090x** [comment]
Install iosevka nerd patched fonts.
