### ISSUE TITLE
polybar-6; some of the modules are not loaded

### ISSUE THREAD

**Issue by issadarkthing** [adi1090x/polybar-themes#38]
![image](https://user-images.githubusercontent.com/50593529/76937871-8fcaca00-6930-11ea-90a6-ed2a97eb4815.png)

some of the modules are not loaded eventhough it is listed in the modules-list
![image](https://user-images.githubusercontent.com/50593529/76938011-dc160a00-6930-11ea-9b15-b9634504e731.png)

**Comment by adi1090x** [comment]
edit the config file and change like, network interface name and other stuff.
