### ISSUE TITLE
how to get powermenu work

### ISSUE THREAD

**Issue by tjw0lf** [adi1090x/polybar-themes#4]
How can i get the powermenu to work in xfce. I'm using your polybar if you can help me

**Comment by haideralipunjabi** [comment]
Provide more details. Is the menu able to open? or Are the buttons not working? Every button or only some of them?

**Comment by tjw0lf** [comment]
its not even opening when i click

**Comment by haideralipunjabi** [comment]
Do you have [rofi](https://github.com/DaveDavenport/rofi) installed?

**Comment by adi1090x** [comment]
> How can i get the powermenu to work in xfce. I'm using your polybar if you can help me

I've included the scripts in the repo, make sure you've rofi installed in your os.

**Comment by AstroTheAstronaut** [comment]
Hi, Adi! I have both rofi and your script installed. It still doesn't work though. When I click on the power button nothing happens. Any help?

**Comment by adi1090x** [comment]
Make sure the script is executable.
