### ISSUE TITLE
mpd objects don't appear (Polybar-8)

### ISSUE THREAD

**Issue by alessiocelentano** [adi1090x/polybar-themes#40]
Hi, I've installed Polybar-8 yesterday and it's awesome! I edited Material theme .ini files to make it even cooler and I noticed that there is the music player on the bar by default. I tried to edit settings in all ways but it doesn't appears to me. This happens with all mpd objects (mpd, mpd_i, mpd_bar, mpd_bar_i). What is the problem?

My WM: i3-gaps-rounded-git

**Comment by adi1090x** [comment]
you need to install mpd for that to work.
