### ISSUE TITLE
Trying to track down missing fonts for bar 3

### ISSUE THREAD

**Issue by Godridge** [adi1090x/polybar-themes#41]
Hi, love these bars, would be lost without them

having an issue with bar 3 though, all the text in menus shows up garbled, in the modules.ini as well, example being one of these 

love the bar and want to build off it.  any idea what font I'm missing/have to track down to make the rofi menus work for bar 3?

**Comment by adi1090x** [comment]
screenshot?

**Comment by Godridge** [comment]
I did attempt to install fonts that were included, but am unaware which one I messed up on, or how to go about doing it correctly

![Screenshot from 2020-04-21 13-46-34](https://user-images.githubusercontent.com/8710379/79867906-ff702100-83d6-11ea-93e0-55b16656f8f7.png)

my assumption is arch probably isn't a special case for fonts but appreciate being corrected

**Comment by adi1090x** [comment]
That's an issue with pango, use different font for rofi. Pango doesn't not support bitmap fonts anymore.

**Comment by Godridge** [comment]
For anyone else who needs help with this, enter ~/.config/polybar/scripts , open each one to find where Rofi is called, and change each instance of "Misc Termsyn 12" to a font+size of your choice
