### ISSUE TITLE
Separators bar 5

### ISSUE THREAD

**Issue by dlgeraghty** [adi1090x/polybar-themes#43]
Separators in bar-5 appeard broken by default 
The modules: left-end-top , right-end-top , left-end-bottom and right end bottom all had the same issue, in the content value, the % was in the icon , preventing it from displaying correctly, I suggest you have a look at it
Adding some extra spaces to get the % away, fixed it for me

Otherwise, great job

**Comment by adi1090x** [comment]
i think it's not a issue with everyone. in my case i don't see any % and adding extra spaces alter the layout or bar. anyway thanks.
