### ISSUE TITLE
Can't find rofi themes

### ISSUE THREAD

**Issue by lyiriyah** [adi1090x/polybar-themes#46]
@adi1090x where do you get the rofi themes mentioned?

**Comment by adi1090x** [comment]
Explanation?

**Comment by lyiriyah** [comment]
there are rofi themes for their respective polybar themes so i was wondering where i can get them

**Comment by adi1090x** [comment]
It's inside the script dir of respective polybar

**Comment by broken7c4** [comment]
@adi1090x, I think what @lyiriyah is trying to say is about it. exemple bellow.

In "polybar-1/scripts/sysmenu" rofi has colors theming like this:
![image](https://user-images.githubusercontent.com/64182007/80297006-bf51cb00-8755-11ea-8878-bfbf3771de4b.png)
But as example, "polybar-5/scripts/powermenu" dont have the same colors config in rofi command. At lest for me. rofi dont load theme in polybar-5 and others
![image](https://user-images.githubusercontent.com/64182007/80297033-0344d000-8756-11ea-9027-3eccbdfbbd92.png)

So just let me say. Congrats for the nice job with this themes. And I'm sorry for my english. Its a working in progress. LOL

**Comment by adi1090x** [comment]
yeah, I've updated polybar 1 and 2, and rest will be update by time.
