### ISSUE TITLE
Questions about fonts

### ISSUE THREAD

**Issue by yyy33** [adi1090x/polybar-themes#48]
Could you please tell me how to make the font edge bigger? I tried to increase the size, but it didn't work

**Comment by adi1090x** [comment]
which one are you using?

**Comment by UrosRiznic** [comment]
I installed one of the themes ( polybar-11 ) and everything is working except the icons ?
I have no idea, but they are not showing.
In the part : 
# copy fonts to local fonts dir (i'll put the fonts in all dirs)
cp -r fonts/* ~/.local/share/fonts
insted of  : " ~/.local/share/fonts" i did this : " $HOME/.fonts "

Can you maybe help ? 
Thanks!

**Comment by adi1090x** [comment]
Try putting fonts in the `.local/share/fonts`

**Comment by UrosRiznic** [comment]
I tried putting it in :
1)  usr/share/fonts (i had to change permision for this)
2)  $home/.local/share/fonts (there wasnt fonts dir so i one there)
3)   $home/.local/share/.fonts (there wasnt .fonts dir so i one there)
4)   $home/.fonts (also made that)
5)   $home/fonts (also made that)

and nothing worked :D 
I have no idea how but yea...

**Comment by adi1090x** [comment]
show me the output of - 
`fc-list | grep -i siji`
`fc-list | grep -i scientifica`

**Comment by UrosRiznic** [comment]
it doesnt output anything.

**Comment by adi1090x** [comment]
it shout look like this, which means fonts are installed.
![2020-04-28-144653_431x312_scrot](https://user-images.githubusercontent.com/26059688/80470043-0fe84480-895f-11ea-8639-c1280655b4bf.png)

i don't know what's wrong with your system, which disto are you using?

**Comment by UrosRiznic** [comment]
im using Manjaro i3
Hey if you have discord, maybe we can chat there, it would be much faster hahahha 
YuroshiKun#3039

**Comment by yyy33** [comment]
> it shout look like this, which means fonts are installed.
> ![2020-04-28-144653_431x312_scrot](https://user-images.githubusercontent.com/26059688/80470043-0fe84480-895f-11ea-8639-c1280655b4bf.png)
> 
> i don't know what's wrong with your system, which disto are you using?

Thanks . It ' s taken care of .

**Comment by yyy33** [comment]
Must use monospaced fonts , if you encounter the same problem can refer to .

**Comment by ebiak** [comment]
@UrosRiznic try 
`sudo rm /etc/fonts/conf.d/70-no-bitmaps.conf
fc-cache -f -v` worked for me but im not sure how safe and reliable it is
