### ISSUE TITLE
Polybar-6

### ISSUE THREAD

**Issue by mbajgai** [adi1090x/polybar-themes#50]
Hi @adi1090x I'm running an i3-gaps on Arch Linux right now. You have done a very exceptional job on these polybar themes, and I really appreciate that. Right now, I'm using polybar-6, and I'm only getting a few status bars on the top. I tried using polybar-5, too, but I don't think all the scripts are working, I can only see a few. I'm going to be waiting for your response cheers!

**Comment by adi1090x** [comment]
screenshot?
