### ISSUE TITLE
polybar-4

### ISSUE THREAD

**Issue by lktoby** [adi1090x/polybar-themes#51]
hi, so i followed your instructions to use polybar-4 but i cant change the colour scheme in it?? i mean i wanna use the dark blue theme but when i launch the bash file it gives me the light variant instead and the terminal returned the following error message:
`pgrep: invalid user name: -x
error: Disabling module "mpd" (reason: No built-in support for 'internal/mpd')
error: Disabling module "alsa" (reason: No built-in support for 'internal/alsa')
error: module/backlight: Could not get data (err: XCB_NAME (15))
error: Disabling module "backlight" (reason: Not supported for "eDP-1")
`
im pretty new to polybar so if the question is a bit dumb im sorry ;-; i didnt change anything in the config file

**Comment by adi1090x** [comment]
Why you using bash to change the colorschemes, use the style module, that's what it's purpose.

**Comment by lktoby** [comment]
how can i do that?? I'm sorry I'm pretty new to linux programming and all that ;-;

**Comment by lktoby** [comment]
also the error message appeared when i ran launch.sh

**Comment by adi1090x** [comment]
> To change colors, there is a module (the feather one) added on polybar which changes the colors in Real-time/In-place or whatever you call it.

![img](https://raw.githubusercontent.com/adi1090x/files/master/polybar-themes/previews/preview_cm.png)

And these errors shows that, mpd/alsa not install or polybar complied against there dependencies.
