### ISSUE TITLE
None of the themes work for me

### ISSUE THREAD

**Issue by meta-boy** [adi1090x/polybar-themes#53]
I followed everything in the readme but was not able to get it running.
System Info
```sh
OS: Ubuntu 20.04 LTS x86_64 
Host: VivoBook_ASUS Laptop X505ZA_X505ZA 1.0 
Kernel: 5.4.0-29-generic 
Uptime: 16 mins 
Packages: 2687 (dpkg), 1 (brew), 12 (snap) 
Shell: zsh 5.8 
Resolution: 1920x1080 
WM: i3 
Theme: Layan-dark [GTK2/3] 
Icons: breeze [GTK2/3] 
Terminal: x-terminal-emul 
CPU: AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx (8) @ 2.000GHz 
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
Memory: 3245MiB / 15013MiB 
```
i3-gaps
```
i3 version 4.18.1-146-g66d2eba8 (2020-05-07, branch "gaps-next") © 2009 Michael Stapelberg and contributors
```
![](https://media.discordapp.net/attachments/696592006276710471/708895362965831730/unknown.png)

**Comment by adi1090x** [comment]
You need to install the fonts.

**Comment by meta-boy** [comment]
> You need to install the fonts.

I do have them installed
![](https://cdn.discordapp.com/attachments/696592006276710471/708994794646667344/unknown.png)

**Comment by meta-boy** [comment]
Nevermind, I installed the fonts systemwide and it worked, thanks
