### ISSUE TITLE
Audio module breaking Pulseaudio

### ISSUE THREAD

**Issue by ghost** [adi1090x/polybar-themes#54]
When I mute my sound by clicking on the audio module of polybar theme 4 and unmute my sound it no longer works. I tried looking through the scripts for any clue that causes this problem but couldn't find anything. I'm running Artix Linux with Runit. The only solution to this problem is running "alsactl init" in my terminal.

**Comment by sachiel2008** [comment]
> reinstalling Pulseaudio and rebooting currently.

unni

**Comment by adi1090x** [comment]
Repository Updated, Try again. Reopen if issues are not resolved.
Have a look at [Troubleshooting](https://github.com/adi1090x/polybar-themes#troubleshooting) for very common issues and how to resolve theme.
