### ISSUE TITLE
Can't launch polybar

### ISSUE THREAD

**Issue by gilleslijnzaad** [adi1090x/polybar-themes#58]
Hi @adi1090x, this might be a very dumb question as I'm kind of a noob at i3 and Linux in general. I downloaded the polybar-9 files and put them in `~/.config/polybar`. Now, when I do `~/.config/polybar/launch.sh`, it tells me the following:

`pgrep: invalid user name: -x`
`~/.config/polybar/launch.sh: 12: polybar: not found`

What does this mean? Should I have installed anything, edited anything in my config file? I run Ubuntu 20.04 if that helps.

Cheers!
Gilles

**Comment by adi1090x** [comment]
Install polybar.

**Comment by davidchoo12** [comment]
You can try search for a package `apt search polybar` and if it exists, `apt install polybar`. Otherwise you will need to [build it](https://github.com/polybar/polybar/wiki/Compiling).

**Comment by adi1090x** [comment]
Repository Updated, Try again. Reopen if issues are not resolved.
Have a look at [Troubleshooting](https://github.com/adi1090x/polybar-themes#troubleshooting) for very common issues and how to resolve theme.
