### ISSUE TITLE
Error parsing theme

### ISSUE THREAD

**Issue by varlevi** [adi1090x/polybar-themes#60]
Hi! Beautiful project! I was able to set up the theme (I'm using polybar-13) and the two bars are showing up, however, if I try to click on them, I get the following error:

```
Error Parsing Theme:
/home/pi/.config/polybar/scripts/themes/launcher.rasi
Parser error: Option: icon-theme is not found.
Parser error: Option: drun-display-format is not found.
```

Here's the part of the file concerned:
```
configuration {
    font:                           "Iosevka Nerd Font 10";
    show-icons:                     false;
    icon-theme:                     "Papirus";
    display-drun:                   "";
    drun-display-format:            " {name}";
    threads:                        0;
    scroll-method:                  0;
    disable-history:                false;
    fullscreen:                     false;
        hide-scrollbar:             true;
        sidebar-mode:               false;
    location:                       7;
}
```

The problem is probably simple, but this is my first time ricing and I'm a noob to say the least.

**Comment by nroetert** [comment]
> Hi! Beautiful project! I was able to set up the theme (I'm using polybar-13) and the two bars are showing up, however, if I try to click on them, I get the following error:
> 
> ```
> Error Parsing Theme:
> /home/pi/.config/polybar/scripts/themes/launcher.rasi
> Parser error: Option: icon-theme is not found.
> Parser error: Option: drun-display-format is not found.
> ```
> 
> Here's the part of the file concerned:
> 
> ```
> configuration {
>     font:                           "Iosevka Nerd Font 10";
>     show-icons:                     false;
>     icon-theme:                     "Papirus";
>     display-drun:                   "";
>     drun-display-format:            " {name}";
>     threads:                        0;
>     scroll-method:                  0;
>     disable-history:                false;
>     fullscreen:                     false;
>         hide-scrollbar:             true;
>         sidebar-mode:               false;
>     location:                       7;
> }
> ```
> 
> The problem is probably simple, but this is my first time ricing and I'm a noob to say the least.

Did you go ahead and install the actual Papirus icon theme and Rofi launcher?

> https://github.com/PapirusDevelopmentTeam/papirus-icon-theme

on Arch you can just install with pacman, `$ sudo pacman -S papirus-icon-theme`
Same thing for Rofi '$ sudo pacman -S rofi'

**Comment by adi1090x** [comment]
Repository Updated, Try again. Reopen if issues are not resolved.
Have a look at [Troubleshooting](https://github.com/adi1090x/polybar-themes#troubleshooting) for very common issues and how to resolve theme.
