### ISSUE TITLE
Some icons such as the heart not showing on Polybar 6

### ISSUE THREAD

**Issue by SIX10** [adi1090x/polybar-themes#61]
Some icons aren't showing on Polybar 6. I'm running Manjaro and i3-gaps. The fonts are installed system wide in /usr/share/fonts. Here's a pic:
![2020-05-29-160641_1920x1080_scrot](https://user-images.githubusercontent.com/34385243/83305485-75318e80-a1c6-11ea-86a0-ccf309c80b7b.png)

**Comment by davidchoo12** [comment]
I also encountered this issue. I fixed it by doing `sudo dpkg-reconfigure fontconfig-config` and `sudo rm /etc/fonts/conf.d/70-no-bitmaps.conf && fc-cache`. See https://github.com/polybar/polybar/wiki/Fonts

**Comment by SIX10** [comment]
> I also encountered this issue. I fixed it by doing `sudo dpkg-reconfigure fontconfig-config` and `sudo rm /etc/fonts/conf.d/70-no-bitmaps.conf && fc-cache`. See https://github.com/polybar/polybar/wiki/Fonts

The debugging area in the Polybar's repo sadly didn't work.
I'm on Manjaro and don't have dpkg, do you know of an equivalent I could use?

**Comment by davidchoo12** [comment]
Sorry I've no idea for Manjaro. I'm on Ubuntu and those worked for me. Maybe you can try `xfd -fa siji` to see if it is actually installed?

**Comment by SIX10** [comment]
> Sorry I've no idea for Manjaro. I'm on Ubuntu and those worked for me. Maybe you can try `xfd -fa siji` to see if it is actually installed?
Manjaro sadly doesn't have xfd either. I did fc-list -v | grep siji and it found siji.pcf in /usr/share/fonts/, but I installed siji-git from the AUR and it worked.
