### ISSUE TITLE
Can't add new modules to polybar 6.

### ISSUE THREAD

**Issue by shahid777-py** [adi1090x/polybar-themes#62]
Hello adi Ur work is amazing and I love all Ur themes.
Here in polybar 6 I can't add new. Modules like CPU,ram,temp ..how to solve this issue.

**Comment by nroetert** [comment]
> Hello adi Ur work is amazing and I love all Ur themes.
> Here in polybar 6 I can't add new. Modules like CPU,ram,temp ..how to solve this issue.

What do you mean, when you can't add new modules.
How did you go about trying it? Did you edit the config.ini added them to one modules-right = line or somewhere else?
Did you check the modules.ini file to see if these weren't commented out, or are compatible with your system?

I'm running the Polybar-8 theme and had to change the battery settings to BAT0 and AC for instance to make the battery module work.

**Comment by shahid777-py** [comment]
Yes ...I edited it the config.i I like the usual polybar config editing way..but it doesn't appearing anything.

**Comment by shahid777-py** [comment]
Is the config.ini using any other config or it's just arename of the original config

**Comment by adi1090x** [comment]
Repository Updated, Try again. Reopen if issues are not resolved.
Have a look at [Troubleshooting](https://github.com/adi1090x/polybar-themes#troubleshooting) for very common issues and how to resolve theme.
