### ISSUE TITLE
System tray icons not appearing when using polybar-5

### ISSUE THREAD

**Issue by mjd119** [adi1090x/polybar-themes#63]
Unsure if there is an issue with the theme or my configuration is just wrong. My previous polybar config showed system tray icons by default but the polybar-5 doesn't show the icons even after adding the lines mentioned in the config.ini. 
The output of awk '!/^ *;/ && NF' ~/.config/polybar/config.ini is:

[global/wm]
margin-bottom = 0
margin-top = 0
include-file = ~/.config/polybar/colors.ini
include-file = ~/.config/polybar/modules.ini
include-file = ~/.config/polybar/user_modules.ini
include-file = ~/.config/polybar/bars.ini
[bar/main]
monitor =
monitor-fallback =
monitor-strict = false
override-redirect = false
bottom = false
fixed-center = true
width = 100%
height = 26
offset-x = 0%
offset-y = 0%
background = ${color.bg}
foreground = ${color.fg}
radius-top = 0.0
radius-bottom = 0.0
overline-size = 2
overline-color = ${color.ac}
border-bottom-size = 0
border-color = ${color.ac}
padding = 0
module-margin-left = 0
module-margin-right = 0
font-0 = Iosevka Nerd Font:style=Medium:size=14;3
font-1 = icomoon\-feather:style=Medium:size=14;3
font-2 = Iosevka Nerd Font:style=Medium:size=20;3
font-3 = Iosevka Nerd Font:style=Medium:size=16;3
font-4 = Iosevka Nerd Font:style=Medium:size=11;3
[bar/top]
inherit = bar/main
modules-left = menu title right-end-top left-end-bottom workspaces right-end-top left-end-bottom colors-switch right-end-top
modules-right = left-end-top updates right-end-bottom left-end-top battery checknetwork right-end-bottom left-end-top date sysmenu
enable-ipc = true
[bar/bottom]
inherit = bar/main
bottom = true
modules-left = mpd right-end-bottom left-end-top cpu memory filesystem right-end-bottom 
modules-right = left-end-bottom network right-end-top left-end-bottom volume brightness
enable-ipc = true
[layout]
module-padding = 1
icon-font = 6
bar-format = %{T4}%fill%%indicator%%empty%%{F-}%{T-}
bar-fill-icon = ﭳ
separator =
spacing = 0
dim-value = 1.0
wm-name = i3
locale = 
tray-position = center
tray-detached = false
tray-maxsize = 16
tray-transparent = false
tray-background = ${color.bg}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1.0
 wm-restack = i3
 override-redirect = true
click-left = 
click-middle = 
click-right =
scroll-up =
scroll-down =
double-click-left =
double-click-middle =
double-click-right =
cursor-click = 
cursor-scroll = 
[settings]
throttle-output = 5
throttle-output-for = 10
throttle-input-for = 30
screenchange-reload = false
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over
format-foreground = 
format-background = 
format-underline =
format-overline =
format-spacing =
format-padding =
format-margin =
format-offset =
pseudo-transparency = false

I set the wm-restack and wm-name arguments and added the "override-redirect = true" line mentioned in the config. I followed the directions specified in the wiki and everything else seems to work fine. 
EDIT:
Outputting the log to a file the way the polybar wiki says by adding "2>~/.top.log &" (also one with .bottom.log) after the position argument doesn't show anything in the log that seems relevant. The tray icons show up when I uncomment the bar part in i3 (even while still running polybar).

**Comment by adi1090x** [comment]
Repository Updated, Try again. Reopen if issues are not resolved.
Have a look at [Troubleshooting](https://github.com/adi1090x/polybar-themes#troubleshooting) for very common issues and how to resolve theme.
