### ISSUE TITLE
dropping unmatched character even with all fonts installed for Polybar-12

### ISSUE THREAD

**Issue by MuizU** [adi1090x/polybar-themes#68]
I have installed the waffle font
`fc-list | grep waffle
/home/muiz_bspwm/.local/share/fonts/waffle-10.bdf: waffle:style=Regular`  

 and the scientifica font

`fc-list | grep scientifica
/home/muiz_bspwm/.local/share/fonts/scientifica/scientificaBold-11.bdf: scientifica:style=Bold
/usr/share/fonts/TTF/scientifica.ttf: scientifica:style=Medium
/home/muiz_bspwm/.local/share/fonts/scientifica/scientificaItalic-11.bdf: scientifica:style=Italic
/usr/share/fonts/TTF/scientificaItalic.ttf: scientifica:style=Medium
/home/muiz_bspwm/.local/share/fonts/scientifica/scientifica-11.bdf: scientifica:style=Regular
/usr/share/fonts/TTF/scientificaBold.ttf: scientifica:style=Bold`

but I still get the error  "dropping unmatched character"

**Comment by owenrumney** [comment]
Hey @MuizU  - I had to do `sudo mv /etc/fonts/conf.d/70-no-bitmaps.conf /etc/fonts/conf.d/70-no-bitmaps.conf.bak` to get this to work. 

The font is a bitmap font and they were being disabled till I ran this

**Comment by BlueLovin** [comment]
Worked for me, I changed the readme and opened a pull request.

**Comment by adi1090x** [comment]
Repository Updated, Try again. Reopen if issues are not resolved.
Have a look at [Troubleshooting](https://github.com/adi1090x/polybar-themes#troubleshooting) for very common issues and how to resolve theme.
