### ISSUE TITLE
Issue with unmatched character

### ISSUE THREAD

**Issue by ClassesNotStructs** [adi1090x/polybar-themes#7]
when I launch polybar 5 I get the dropping unmatched errors like:
warn: Dropping unmatched character  (U+e0ba)
warn: Dropping unmatched character ﭳ (U+fb73)
warn: Dropping unmatched character ﭳ (U+fb73)
warn: Dropping unmatched character ﭳ (U+fb73)
warn: Dropping unmatched character ﭳ (U+fb73)
warn: Dropping unmatched character ﭳ (U+fb73)
warn: Dropping unmatched character  (U+e0be)
warn: Dropping unmatched character  (U+e0b8)
warn: Dropping unmatched character  (U+e0be)
warn: Dropping unmatched character  (U+e0b8)
warn: Dropping unmatched character  (U+e0be)
warn: Dropping unmatched character  (U+e0b8)

I am fairly certain that fb73 belongs to an arabic font and all of the e0b's belong to utf csur, however, these are already installed and it doesn't seem to detect them. The bar looks a bit off as the center is transparent rather than having the diagonal lines in the screenshot

I found the part of the config containing these configurations at the bottom of user_modules.ini

**Comment by adi1090x** [comment]
Just install the fonts I've mentioned and provided also.

**Comment by sirusss** [comment]
Also having the same issue. I'm on Arch KDE and installed all necessary fonts.
