### ISSUE TITLE
Is there a missing slash on the Readme instructions to copy fonts?

### ISSUE THREAD

**Issue by hobbsy** [adi1090x/polybar-themes#71]
In the example instructions at the top of the readme it says:

`# copy fonts to local fonts dir (i'll put the fonts in all dirs)`
`cp -r fonts/* ~/.local/share/fonts`

is this missing a / after fonts?

eg. should it be
`cp -r fonts/* ~/.local/share/fonts/`

**Comment by adi1090x** [comment]
Repository Updated, Try again. Reopen if issues are not resolved.
Have a look at [Troubleshooting](https://github.com/adi1090x/polybar-themes#troubleshooting) for very common issues and how to resolve theme.
