### ISSUE TITLE
Using HiDPI screen and polybar-theme-12 / can font be increased?

### ISSUE THREAD

**Issue by hobbsy** [adi1090x/polybar-themes#72]
Hi there,

I'm using a ThinkPad X1C6 (running Manjaro KDE) and I believe the screen res is 2560x1440 (HiDPI?)

On a few other of adi's polybar-themes-* I have been able to successfully use the setting in config:
dpi = 192

to make the fonts in the top bar a readable size

But this doesn't seem to work in polybar theme 12
Is this because it is using a bitmap font waffle (?)
Is there a way to increase the font size?
Maybe instead of waffle-10.bdf I could try and find a waffle-20.bdf (??)

Or is there a simple fix I can put in the config?

Thanks

**Comment by quantum-booty** [comment]
I am experiencing a similar issue, the waffle icons are not scalable.

**Comment by quantum-booty** [comment]
@hobbsy Check out bitsnipicas, you can use it to convert bdf into ttf using this in the command line:
`java -jar BitsNPicas.jar convertbitmap -f ttf -o myfont.ttf myfont.bdf
`

**Comment by adi1090x** [comment]
Repository Updated, Try again. Reopen if issues are not resolved.
Have a look at [Troubleshooting](https://github.com/adi1090x/polybar-themes#troubleshooting) for very common issues and how to resolve theme.
