### ISSUE TITLE
Polybar for ratpoison

### ISSUE THREAD

**Issue by drmarwat** [adi1090x/polybar-themes#73]
Could you make a polybar dots for ratpoison as well? I am using polybar 1with ratpoison but it does not show me battery .

**Comment by adi1090x** [comment]
Repository Updated, Try again. Reopen if issues are not resolved.
Have a look at [Troubleshooting](https://github.com/adi1090x/polybar-themes#troubleshooting) for very common issues and how to resolve theme.
