### ISSUE TITLE
How can I change shortcuts icons by workspaces in theme 1?

### ISSUE THREAD

**Issue by rubusarbaro** [adi1090x/polybar-themes#75]
I want to substitute the icons of terminal, file administrator, browser and settings by the workspaces.
The workspaces' module remains as the original in the config.ini file, but I don't know what to change.
![barPoly](https://user-images.githubusercontent.com/61021296/93536576-ef6d5680-f90e-11ea-9f5f-dacaa19c8ea5.png)

**Comment by adi1090x** [comment]
Repository Updated, Try again. Reopen if issues are not resolved.
Have a look at [Troubleshooting](https://github.com/adi1090x/polybar-themes#troubleshooting) for very common issues and how to resolve theme.
