### ISSUE TITLE
MPD module is not working.

### ISSUE THREAD

**Issue by rubusarbaro** [adi1090x/polybar-themes#76]
First of all, a little summary of my system:
**OS:** Ubuntu 20.04
**DE:** Regolith
**WM:** i3

When I reproduce any song on any player (VLC, Rhythmbox, YouTube, AppleMusic, etc...) the song's name and controls are not shown.

**Comment by JeppeX** [comment]
Mpd module is not supposed to do that. Mpd stands for "music player daemon" and it's a player itself. So it's not supposed to work on other players.
