### ISSUE TITLE
the tty symbol is different with the readme picture

### ISSUE THREAD

**Issue by KairuiLiu** [adi1090x/polybar-themes#78]
the tty symbol is different with the readme picture
![0Uruh6.png](https://s1.ax1x.com/2020/10/06/0Uruh6.png)

**Comment by BrianDelalex** [comment]
Hi,
I used to have the same issue. What you need to do is to set the value icon-x in modules.ini with the names of your workspaces. For example with i3 the name of a workspace is define with ' set $ws1 "1" ' . In this case the workspace name is 1 so just set icon-1 = 1 and you'll be done.
![Screen Capture_select-area_20201028223632](https://user-images.githubusercontent.com/50317889/97499423-1be4ab80-196e-11eb-9762-494376ec4389.png)

**Comment by KairuiLiu** [comment]
Thanks I havs sove it 
I install all the font packages of polybar-theme(not the fonts in a folder like `polybar-5` but `polybar-1` to `polybar-13` ) and it display normally
