### ISSUE TITLE
Dropping unmatched characters, even after following the readme step by step (polybar 6)

### ISSUE THREAD

**Issue by Pistrie** [adi1090x/polybar-themes#79]
I did every step in the readme, but Im still getting errors, and the bar looks weird because its not showing any of the fonts.
Also, I'm using a desktop, so I will need to find replacements for the disabled modules

![Screenshot_20201010_115504](https://user-images.githubusercontent.com/39904003/95652231-e0ce2580-0aef-11eb-88f2-e2e9ccb25762.png)

**Comment by jacksonSingleton** [comment]
I know this is an old issue. Did you ever resolve this? If not, what distro are you using, and what happens if you run `fc-match siji` ?

**Comment by Pistrie** [comment]
I was not able to resolve this. I think I was using Manjaro at the time, but I switched to Arco shortly after.
