### ISSUE TITLE
Poly-4 Icons

### ISSUE THREAD

**Issue by ITZmyGitHub** [adi1090x/polybar-themes#8]
Having issues whenever I run ./launch.sh, it seems like the icons are missing. Any idea what could be causing this as they're included in the repo?

**Comment by adi1090x** [comment]
You need to install the fonts, copy the fonts to "/usr/share/fonts" or in local directory.

**Comment by manning390** [comment]
Checking the config, the font name is `icomoon-feather` if you installed the icons with a `.ttf` file in your `~/.fonts` or `/usr/share/fonts/` folder make they are named correctly.

**Comment by manning390** [comment]
Even with the fonts installed I am getting unmatched character errors with the tester. Can you provide your font file?

**Comment by rikusen0335** [comment]
Same issue here, I have installed but still missing icons.
In arch linux, is that correct to install these fonts [Siji(Icon)](https://aur.archlinux.org/packages/siji-git), [Termsyn(Text)](https://aur.archlinux.org/packages/termsyn-font/), [Iosevka(Other)](https://aur.archlinux.org/packages/ttf-iosevka)?

**Comment by rikusen0335** [comment]
Sorry I was talking about 6's font...

**Comment by SebastianLloret** [comment]
I had this problem on Arch. Installing nerd-fonts-complete from the AUR fixed the issue.

**Comment by DevGrohl** [comment]
For everyone with problems installing the fonts, there is a folder named "fonts" in the polybar-4 folder. You can copy the "icomoon-feather.ttf" to your global or personal font directory and reload the fonts.

https://wiki.archlinux.org/index.php/fonts#Manual_installation
