### ISSUE TITLE
Not able to change colours

### ISSUE THREAD

**Issue by AwareSuperCC** [adi1090x/polybar-themes#83]
I followed the Read.me and installed it perfectly, but when I right-click the menu icon and select a colour the bar refreshes but colour remains the same. Where can I change the initial colour to deep-purple?
Thanks in Advance

**Comment by adi1090x** [comment]
Repository Updated, Try again. Reopen if issues are not resolved.
Have a look at [Troubleshooting](https://github.com/adi1090x/polybar-themes#troubleshooting) for very common issues and how to resolve theme.
