### ISSUE TITLE
Polybar-1 showing only 2 workspaces

### ISSUE THREAD

**Issue by dhelbegor** [adi1090x/polybar-themes#84]
Workspaces only shows 1 and 2, if I have more than 2 active workspaces they are hidden. how can I solve this issue?

I'm using the Polybar-1 default config with a monitor of 27' with main width 100% I don't know if it reflects on workspaces.

**Comment by JeppeX** [comment]
You can look at `~/.config/polybar/config.ini`. There is a section named `[module/workspaces]`. This is all the config regarding workspaces in this theme so you can try to fiddle with that. I use i3 and it worked for me out of the box.

**Comment by adi1090x** [comment]
Repository Updated, Try again. Reopen if issues are not resolved.
Have a look at [Troubleshooting](https://github.com/adi1090x/polybar-themes#troubleshooting) for very common issues and how to resolve theme.
