### ISSUE TITLE
Polybar-3 Not Autostarting

### ISSUE THREAD

**Issue by jacksonSingleton** [adi1090x/polybar-themes#86]
I've tried polybar-1 and polybar-6  as well. For some reason polybar-3 won't launch from bspwmrc. Running _launch.sh_ works just fine. I've tried changing config files, as well as launching it from .xinitrc instead. Really would love to know if anyone else has run into this issue. If I had to guess it might have something to do with being hung on one of the config starts.

**Comment by adi1090x** [comment]
Repository Updated, Try again. Reopen if issues are not resolved.
Have a look at [Troubleshooting](https://github.com/adi1090x/polybar-themes#troubleshooting) for very common issues and how to resolve theme.
