### ISSUE TITLE
Change non-functional text labels to type custom/text type.

### ISSUE THREAD

**Issue by shivanshu-semwal** [adi1090x/polybar-themes#87]
https://github.com/adi1090x/polybar-themes/blob/b61cdcd71a3ae4044ef0deef4f30f4ab5c39fb97/polybar-8/modules.ini#L327
This duplicate module for displaying the symbol of clock removes the functionality of previous `time-alt` option `date` module.
- When we click the any one of these two module (`date` and `date_i`) it just toggles the symbol and not the format of clock provided by `time-alt`. 
- And even on changing the order of modules in file it still toggles the symbol. 
- And if we don't provide the `time-alt` symbol for the `date_i` module the symbol disappear on clicking the module. 

The only option is to change this module type to `custom/text`.
```ini
[module/date_i]
type = custom/text
;calendar symbol in place of _
content = _

; "content" has the same properties as "format-NAME"
content-background = ${color.red}
content-foreground = ${color.fg}
content-padding = 1
```

**Comment by adi1090x** [comment]
Repository Updated, Try again. Reopen if issues are not resolved.
Have a look at [Troubleshooting](https://github.com/adi1090x/polybar-themes#troubleshooting) for very common issues and how to resolve theme.
