### ISSUE TITLE
Dropping unmatched characters

### ISSUE THREAD

**Issue by yafp** [adi1090x/polybar-themes#9]
Hi,

i am trying to use your Polybar theme 6.
When i start polybar by executing `launch.sh` i get an error output about some dropping  unmatched characters (only those 4):

**Regarding dropping  unmatched characters:**

```
warn: Dropping unmatched character  (U+e107)
warn: Dropping unmatched character  (U+e05d)
warn: Dropping unmatched character  (U+e017)
warn: Dropping unmatched character  (U+e00d)
```

There might be a connection to #7 but ....
I am having trouble to debug that, as i am unsure which font it is missing.
I already added the fonts from the repository (v6) to my local font folder in `~/.local/fonts`, but without success.

**Regarding color-changer:**
The heart symbol (color-changer) to change colors isn't displayed either.
EDIT:  i was missing `rofi`. Maybe rofi should be mentioned as requirement

**Regarding Style changer**
> How To : Left click to change colors and right click to change style of the bar.

Left or right click on what? You might consider explaining that a bit more detailed in the README.md.

EDIT:  i was missing `rofi`. Maybe rofi should be mentioned as requirement

Any help is appreciated & big thanks for your work in those themes.

**Comment by adi1090x** [comment]
I've explained and mentioned everything.
And for that dropping character issue, try putting those fonts in /usr/share/fonts.
