### ISSUE TITLE
ROFI modules not working

### ISSUE THREAD

**Issue by ashwinnatraj97** [adi1090x/polybar-themes#90]
I am using Ubuntu 16.04 with i3wm and polybar. polybar configuration is fine but the rofi modules for powermenu and launcher aren't working and shows the following error.

Error while parsing theme
- Parser error: Option: icon-theme is not found
- Parser error: Option: drun-display-format is not found.

I have installed the fonts too. 
![Screenshot from 2020-12-27 19:40:36](https://user-images.githubusercontent.com/19239465/103172836-5c807880-487c-11eb-91da-2a3885bc5188.png)
![Screenshot from 2020-12-27 19:40:49](https://user-images.githubusercontent.com/19239465/103172840-5f7b6900-487c-11eb-9a25-882d7b795202.png)

**Comment by dein0s** [comment]
It seems that your rofi version is out of date, therefore it can't handle some of the newest options.
`drun-display-format` option was added in version 1.5.2, current version is 1.6.1
```
$ rofi -v
Version: 1.6.1
```

**Comment by adi1090x** [comment]
Update rofi.
